# https://taskfile.dev

version: '3'

tasks:
  init:
    cmds:
      - git config --local core.hooksPath .githooks/
  rebuild:
    cmds:
      - dotnet clean
      - dotnet build-server shutdown
      - dotnet build